### ISSUE TITLE
Is the source code for DVoaMap available?

### ISSUE THREAD

**Issue by ms4sman** [VE3NEA/DVOACAP#2]

**Comment by VE3NEA** [comment]
No, DVoaMap is only a viewer for the prediction results, it comes without the source code.

**Comment by ms4sman** [comment]
Alright, understood. I was just wondering about looking at how you went about plotting the data to a map.

Thanks!

**Comment by VE3NEA** [comment]
An example of plotting the data on the map is available in my other project, [ft8_mapper](https://github.com/VE3NEA/ft8_mapper)

**Comment by ms4sman** [comment]
Ah, I hadn't looked at that project yet. That's very interesting! Thank you for your contributions to the ham community!
