### ISSUE TITLE
Small-value frequency inputs crash dvoa.dll

### ISSUE THREAD

**Issue by WheezyE** [VE3NEA/DVOACAP#3]
Hey there,

First of all, thank you for doing such an incredible job of reversing this Fortran program into a more modern / readable / open format.  The users of Winlink / RMS Express utilize your library every day without even knowing, as it is a key component in the HF Channel Selection Browser in RMS Express (dvoa.dll is used for propagation prediction of each channel so users can pick the best frequency to use to send data to the Winlink network from their location).

I'm currently trying to run RMS Express on Linux using Wine (with an open-source reverse-engineered version of MS.NET called [wine-mono](https://github.com/madewokherd/wine-mono)).  wine-mono crashes when dvoa.dll throws a Delphi exception from a crash.  I noticed that dvoa.dll crashes when small-value frequencies are input into it.  Windows/MS.NET normally handles these `0x0eedfade` Delphi exceptions using its SEH Exception Handler, but wine-mono doesn't know how to handle these exceptions yet.

Bug(?):
 - In my testing, the crash happens if RMS Express sends dvoa.dll anything smaller than `"Freqs": [0.05]` (though this puzzling since [DVoaDllTestCmd.exe](https://github.com/VE3NEA/DVOACAP/blob/master/DVoaDllTestCmd/DVoaDllTestCmd.exe) only accepts a minimum input frequency of `"Freqs": [0.062000001]`).
 - I was wondering if this was a bug, or if the prediction engine just isn't made to calculate small-value frequencies.
 - I also wanted to ask if there would be a way to add some exception handling in dvoa.dll that catches these crashes and reports an error instead of sending out a Delphi crash exception (`0x0eedfade`).

Errors downstream from the Delphi crash:
 - RMS Express with Linux/Wine + wine-mono crashes when dvoa.dll throws its Delphi exception.
 - RMS Express with Windows + MS.NET 4.6 notices the Delphi exception an ignores it, (*Improved dotNET Tracer shows MS.NET's SEHException method running if a small-value frequency is sent to dvoa.dll through RMS Express*), but I believe results in a false "0" propagation prediction estimate for a small-value frequency.

Possible solutions:
 - If small-value frequency calculation errors are just a limitation of the original VOACAP algorithm, then I think ultimately the most-direct fix would be just to have the RMS Express devs catch small-value frequencies before they get fed into dvoa.dll so that those stations don't falsely predict "0" propagation (on windows) or crash (in wine-mono).
 - If VOACAP is capable of calculating propagations for small-value frequencies though, then fixing this bug would allow RMS Express to report correct propagation predictions for small-value input frequencies.
 - Having dvoa.dll catch the small-value input frequencies would prevent wine-mono from crashing, but would still result in RMS Express predicting "0" propagation for small-value frequencies in RMS Express in Wine+wine-mono & Windows+MS.NET.
 - Having wine-mono catch and ignore the Delphi exception would solve the wine-mono crash, but would also still result in false "0" propagation predictions for small-value frequencies.  *I've [reached out](https://bugs.winehq.org/show_bug.cgi?id=52131) to the wine-mono / CodeWeaver devs to see if they can implement handling for Delphi exceptions too.*
 
Anyway, let me know what you think!
73, de KI7POL
Eric

**Comment by VE3NEA** [comment]
The VOACAP algorithm works in the frequency range from 2 MHz to 30 MHz. It has poor accuracy below 4 MHz and falls apart completely below 2 MHz. Please see [this paper](https://www.voacap.com/lowband.html) for the details.

**Comment by WheezyE** [comment]
Ah! Thank you. That makes a lot more sense.

I also realized after looking through the dvoa.dll code a bit more that the `Exception500: Error computing prediction: Assertion failure` that is throwing the exception that I bet wine-mono is seeing as `0x0eedfade` is [normal behavior](https://github.com/VE3NEA/DVOACAP/blob/6032495873534dec33b124b722c9a67071af9ee1/DVoaDll/dvoa.dpr#L59).

I decided to compare the frequency of the station that is crashing dvoa.dll (and RMS Express) from the RMS Express station database (`RMS Channels.dat`) with this online [Gateway Channels database](https://www.winlink.org/content/gateway_channels) (select ARDOP) and found that the 9W2RUT station's input frequency is probably a typo in `RMS Channels.dat`
```
Station | Freq Database | Our Frequency | RMS Channels.dat -> dvoa.dll (as sent from RMS)
        |     (KHz)     |    (MHz)      |        (Hz)      ->        (MHz)
------------------------------------------------------------------------------------
DA5UDI  | 7,051.400 KHz | 7.051400 MHz  | 7051400          -> "Freqs": [ 7.05] (works)
test    |      n/a      | 0.054999 MHz  |   54999          -> "Freqs": [ 0.05] (Delphi crash)
9W2RUT  | 7,093.000 KHz | 0.007093 MHz  |    7093 (TYPO!)  -> "Freqs": [ 0.01] (Delphi crash)
```

Knowing all this, I think I'll reach out to the RMS Express devs to have them fix the typo in the 9W2RUT station in `RMS Channels.dat`, but I'll also suggest to them some exception handling in RMS Express to warn users about calculating frequencies below 2 MHz. That should hopefully fix RMS Express propagation prediction accuracies in any future cases like this.

This ended up being kind of useful for wine-mono development too. I think it's good to know that Delphi/Pascal programs throwing 0x0eedfade exceptions from normal, programmer-generated, error messages might crash wine-mono.  I'm reaching out to the wine-mono devs to see if they can try ignoring Delphi exceptions in the future to improve their version of MS.NET's "Structured Exception Handling".
