### ISSUE TITLE
64-bit build?

### ISSUE THREAD

**Issue by ms4sman** [VE3NEA/DVOACAP#4]
Hi there,

This DLL is compiled for 32 bit it looks like. Is there any chance of getting a version of it compiled for 64 bit?

Thanks for your hard work on DVOA, I really appreciate it!

Thanks,

**Comment by VE3NEA** [comment]
I have [added ](https://github.com/VE3NEA/DVOACAP/commit/46f1e4fa11e4cb42e6afc196913e365da8f9b6a7)the FP project file that I use to build a 64-bit version of the dll

**Comment by ms4sman** [comment]
Thank you! Works great!

de KE0TCF
